export const countriesData = [
  "Montenegro",
  "New Zealand",
  "Belarus",
  "Libyan Arab Jamahiriya",
  "Saint Helena",
  "Solomon Islands",
  "Saint Barthelemy",
  "Iceland",
  "United States of America",
  "Guinea-Bissau",
  "Bolivia",
  "Austria",
  "Sierra Leone",
  "Libyan Arab Jamahiriya",
  "Panama",
  "Ecuador",
  "South Africa",
  "Saint Pierre and Miquelon",
  "Pakistan",
  "Tunisia",
  "Aruba",
  "Saint Kitts and Nevis",
  "Brazil",
  "Papua New Guinea",
  "Saint Martin",
];
